In [1]:
import numpy as np

In [2]:
height = np.round(np.random.normal(1.75,0.2,5000),2)
weight = np.round(np.random.normal(60.32,15,5000),2)

In [3]:
height

array([1.76, 1.73, 1.59, ..., 1.77, 1.85, 1.84])

In [4]:
weight

array([57.49, 67.57, 47.72, ..., 62.16, 66.27, 54.31])

In [5]:
type(height)

numpy.ndarray

In [6]:
height.shape

(5000,)

In [8]:
all = np.column_stack((height,weight))

In [9]:
all

array([[ 1.76, 57.49],
       [ 1.73, 67.57],
       [ 1.59, 47.72],
       ...,
       [ 1.77, 62.16],
       [ 1.85, 66.27],
       [ 1.84, 54.31]])

In [11]:
np.mean(all[:,0])

1.747196

In [12]:
np.mean(all[0:,1])

60.33528199999999