In [1]:
import numpy as np

In [2]:
height = np.round(np.random.normal(1.75,0.20,5000),2)

In [3]:
height

array([1.77, 1.76, 1.44, ..., 1.7 , 1.96, 1.62])

In [4]:
weight = np.round(np.random.normal(60.32,15,5000),2)

In [5]:
np_city = np.column_stack((height,weight))

In [6]:
np_city

array([[  1.77, 102.92],
       [  1.76,  66.55],
       [  1.44,  55.44],
       ...,
       [  1.7 ,  28.41],
       [  1.96,  77.22],
       [  1.62,  40.42]])

In [7]:
np_city[:,0]

array([1.77, 1.76, 1.44, ..., 1.7 , 1.96, 1.62])

In [8]:
np_city[:,1]

array([102.92,  66.55,  55.44, ...,  28.41,  77.22,  40.42])